[workspace]
members = [
  "backend",
  "prisma-cli"
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1

[workspace.dependencies]

[workspace.dependencies.prisma-client-rust]
git = "https://github.com/Brendonovich/prisma-client-rust"
default-features = false
features = ["sqlite"]
